
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-dining-f24-13
owner: ucsb-cs156-f24
repo_name: proj-dining-f24-13
pull_requests: [{"author":{"id":"MDQ6VXNlcjYxNjMyNjc4","is_bot":false,"login":"emiz39","name":"Emily Z"},"headRefName":"ez-reviewtables2","number":40,"title":"Created ReviewTable Component + Tests","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-13/pull/40"},{"author":{"id":"U_kgDOBtkPHg","is_bot":false,"login":"clevermonkey16","name":""},"headRefName":"sj-diningcommonsplaceholder","number":29,"title":"sj-Create placeholder page for individual dining commons","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-13/pull/29"},{"author":{"id":"MDQ6VXNlcjYxNjMyNjc4","is_bot":false,"login":"emiz39","name":"Emily Z"},"headRefName":"ez-reviewtable","number":28,"title":"added reviewFixtures","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-13/pull/28"},{"author":{"id":"U_kgDOBtkPHg","is_bot":false,"login":"clevermonkey16","name":""},"headRefName":"sj-reviewsplaceholder","number":26,"title":"sj-create placeholder page for reviews at /reviews/:itemid","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-13/pull/26"},{"author":{"id":"U_kgDOBtkPHg","is_bot":false,"login":"clevermonkey16","name":""},"headRefName":"sj-moderateplaceholder","number":25,"title":"sj-add placeholder page /moderate","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-13/pull/25"},{"author":{"id":"U_kgDOBtkPHg","is_bot":false,"login":"clevermonkey16","name":""},"headRefName":"sj-indexplaceholder","number":24,"title":"sj-create a placeholder page at the url /myreviews","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-13/pull/24"},{"author":{"id":"U_kgDOBtxmGw","is_bot":false,"login":"st4lemon","name":""},"headRefName":"dq-ReviewBackendDatabase","number":23,"title":"dq-added reviews database table (entity, repository, migration)","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-13/pull/23"}]
