
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-dining-f24-13
owner: ucsb-cs156-f24
repo_name: proj-dining-f24-13
pull_requests: [{"author":{"id":"U_kgDOCMRqBA","is_bot":false,"login":"AnvithaKosuri","name":""},"headRefName":"ak-diningcommonstable","number":50,"title":"Ak diningcommonstable","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-13/pull/50"},{"author":{"id":"U_kgDOBtxmGw","is_bot":false,"login":"st4lemon","name":""},"headRefName":"dq-ReviewBackendGetModeration","number":48,"title":"dq-ReviewBackend get reviews needing moderation + tests","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-13/pull/48"},{"author":{"id":"U_kgDOBtxmGw","is_bot":false,"login":"st4lemon","name":""},"headRefName":"dq-ReviewBackendGetByUser","number":47,"title":"dq-ReviewBackend get by user endpoint + tests","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-13/pull/47"},{"author":{"id":"U_kgDOBtxmGw","is_bot":false,"login":"st4lemon","name":""},"headRefName":"dq-ReviewBackendPostGetall","number":46,"title":"dq-ReviewBackend post/get all endpoints + tests","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-13/pull/46"},{"author":{"id":"U_kgDOCMRqBA","is_bot":false,"login":"AnvithaKosuri","name":""},"headRefName":"ak-diningcommonsfixtures","number":44,"title":"ak-added dining commons fixtures","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-13/pull/44"}]
