
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f24/proj-dining-f24-13
owner: ucsb-cs156-f24
repo_name: proj-dining-f24-13
pull_requests: [{"author":{"id":"U_kgDOBtkPHg","is_bot":false,"login":"clevermonkey16","name":""},"headRefName":"shivanimadhan-meals-endpoint","number":53,"title":"Shivanimadhan meals endpoint (just to see what changed)","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-13/pull/53"},{"author":{"id":"U_kgDOBtxmGw","is_bot":false,"login":"st4lemon","name":""},"headRefName":"dq-ReviewBackendModerationPut","number":52,"title":"dq-ReviewBackend GET reviews needing moderation, PUT endpoints to update a user's review and moderate a review","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-13/pull/52"},{"author":{"id":"MDQ6VXNlcjYxNjMyNjc4","is_bot":false,"login":"emiz39","name":"Emily Z"},"headRefName":"ez-addtable","number":51,"title":"ez - add reviewtable to /myreview page","url":"https://github.com/ucsb-cs156-f24/proj-dining-f24-13/pull/51"}]
